"""empty message

Revision ID: 524fd79356da
Revises: aeeb082da91f
Create Date: 2019-07-27 17:22:20.213093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524fd79356da'
down_revision = 'aeeb082da91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
